package pnp.compiler.model;

public enum Operator {
    ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, MODULO,
    EQUALITY, INEQUALITY, LESS_THAN, LESS_THAN_EQUAL, GREATER_THAN, GREATER_THAN_EQUAL,
    NOT, AND, OR, XOR,
    NONE
}
